/*This file has been autogenerated, please do not edit it.*/

package com_sarrubia_eventbus_avro_example

// EventMetadataAVSC Avro schema to send to Schema Registry
const EventMetadataAVSC = "{\"type\":\"record\",\"name\":\"EventMetadata\",\"namespace\":\"com.sarrubia.eventbus.avro.example\",\"doc\":\"\",\"fields\":[{\"name\":\"id\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"key\",\"type\":[\"null\",{\"avro.java.string\":\"String\",\"type\":\"string\"}],\"default\":null},{\"name\":\"version\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"creationLong\",\"type\":\"long\",\"default\":0},{\"name\":\"type\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"}]}"

// EventMetadataSubject schema registry subject
const EventMetadataSubject = "com.sarrubia.eventbus.avro.example.EventMetadata"

// EventMetadataBase
type EventMetadataBase struct {
	Id           string  `avro:"id"`
	Key          *string `avro:"key"`
	Version      string  `avro:"version"`
	CreationLong int64   `avro:"creationLong"`
	Type         string  `avro:"type"`
}

// Schema [REQUIRED] returns the schema const that belongs to EventMetadata
// Important: the receiver MUST NOT be a pointer in order to assert true against schema.EventSchemaInterface
func (e EventMetadataBase) Schema() string {
	return EventMetadataAVSC
}
