/*This file has been autogenerated, please do not edit it.*/

package com_sarrubia_eventbus_avro_example

// UserLoginAttemptEventAVSC Avro schema to send to Schema Registry
const UserLoginAttemptEventAVSC = "{\"type\":\"record\",\"name\":\"UserLoginAttemptEvent\",\"namespace\":\"com.sarrubia.eventbus.avro.example\",\"doc\":\"example app' schema\",\"fields\":[{\"name\":\"email\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"ip\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"date\",\"type\":\"long\",\"default\":0},{\"name\":\"result\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"metadata\",\"type\":{\"items\":{\"type\":\"com.sarrubia.eventbus.avro.example.EventMetadata\"},\"type\":\"array\"},\"default\":null}]}"

// UserLoginAttemptEventSubject schema registry subject
const UserLoginAttemptEventSubject = "com.sarrubia.eventbus.avro.example.UserLoginAttemptEvent"

// UserLoginAttemptEventBase example app' schema
type UserLoginAttemptEventBase struct {
	Email    string          `avro:"email"`
	Ip       string          `avro:"ip"`
	Date     int64           `avro:"date"`
	Result   string          `avro:"result"`
	Metadata []EventMetadata `avro:"metadata"`
}

// Schema [REQUIRED] returns the schema const that belongs to UserLoginAttemptEvent
// Important: the receiver MUST NOT be a pointer in order to assert true against schema.EventSchemaInterface
func (e UserLoginAttemptEventBase) Schema() string {
	return UserLoginAttemptEventAVSC
}
