/*This file has been autogenerated, please do not edit it.*/

package com_sarrubia_eventbus_avro_example_level2

// EventMetadataLevel2Bis2AVSC Avro schema to send to Schema Registry
const EventMetadataLevel2Bis2AVSC = "{\"type\":\"record\",\"name\":\"EventMetadataLevel2Bis2\",\"namespace\":\"com.sarrubia.eventbus.avro.example.level2\",\"doc\":\"\",\"fields\":[{\"name\":\"id\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"key\",\"type\":[\"null\",{\"avro.java.string\":\"String\",\"type\":\"string\"}],\"default\":null},{\"name\":\"versionXYZ\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"creationLong\",\"type\":\"long\",\"default\":0},{\"name\":\"type\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"}]}"

// EventMetadataLevel2Bis2Subject schema registry subject
const EventMetadataLevel2Bis2Subject = "com.sarrubia.eventbus.avro.example.level2.EventMetadataLevel2Bis2"

// EventMetadataLevel2Bis2Base
type EventMetadataLevel2Bis2Base struct {
	Id           string  `avro:"id"`
	Key          *string `avro:"key"`
	VersionXYZ   string  `avro:"versionXYZ"`
	CreationLong int64   `avro:"creationLong"`
	Type         string  `avro:"type"`
}

// Schema [REQUIRED] returns the schema const that belongs to EventMetadataLevel2Bis2
// Important: the receiver MUST NOT be a pointer in order to assert true against schema.EventSchemaInterface
func (e EventMetadataLevel2Bis2Base) Schema() string {
	return EventMetadataLevel2Bis2AVSC
}
