/*This file has been autogenerated, please do not edit it.*/

package com_sarrubia_eventbus_avro_example_level2

// EventMetadataLevel2AVSC Avro schema to send to Schema Registry
const EventMetadataLevel2AVSC = "{\"type\":\"record\",\"name\":\"EventMetadataLevel2\",\"namespace\":\"com.sarrubia.eventbus.avro.example.level2\",\"doc\":\"\",\"fields\":[{\"name\":\"id\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"key\",\"type\":[\"null\",{\"avro.java.string\":\"String\",\"type\":\"string\"}],\"default\":null},{\"name\":\"version\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"creationLong\",\"type\":\"long\",\"default\":0},{\"name\":\"type\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"}]}"

// EventMetadataLevel2Subject schema registry subject
const EventMetadataLevel2Subject = "com.sarrubia.eventbus.avro.example.level2.EventMetadataLevel2"

// EventMetadataLevel2Base
type EventMetadataLevel2Base struct {
	Id           string  `avro:"id"`
	Key          *string `avro:"key"`
	Version      string  `avro:"version"`
	CreationLong int64   `avro:"creationLong"`
	Type         string  `avro:"type"`
}

// Schema [REQUIRED] returns the schema const that belongs to EventMetadataLevel2
// Important: the receiver MUST NOT be a pointer in order to assert true against schema.EventSchemaInterface
func (e EventMetadataLevel2Base) Schema() string {
	return EventMetadataLevel2AVSC
}
