/*This file has been autogenerated, please do not edit it.*/

package com_sarrubia_eventbus_avro_example_level2

// UserLoginAttemptLevel2AVSC Avro schema to send to Schema Registry
const UserLoginAttemptLevel2AVSC = "{\"type\":\"record\",\"name\":\"UserLoginAttemptLevel2\",\"namespace\":\"com.sarrubia.eventbus.avro.example.level2\",\"doc\":\"example app' schema\",\"fields\":[{\"name\":\"email\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"ipMac\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"date\",\"type\":\"long\",\"default\":0},{\"name\":\"result\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"}]}"

// UserLoginAttemptLevel2Subject schema registry subject
const UserLoginAttemptLevel2Subject = "com.sarrubia.eventbus.avro.example.level2.UserLoginAttemptLevel2"

// UserLoginAttemptLevel2Base example app' schema
type UserLoginAttemptLevel2Base struct {
	Email  string `avro:"email"`
	IpMac  string `avro:"ipMac"`
	Date   int64  `avro:"date"`
	Result string `avro:"result"`
}

// Schema [REQUIRED] returns the schema const that belongs to UserLoginAttemptLevel2
// Important: the receiver MUST NOT be a pointer in order to assert true against schema.EventSchemaInterface
func (e UserLoginAttemptLevel2Base) Schema() string {
	return UserLoginAttemptLevel2AVSC
}
