/*This file has been autogenerated, please do not edit it.*/

package com_sarrubia_avro_example_common

// UserAVSC Avro schema to send to Schema Registry
const UserAVSC = "{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.sarrubia.avro.example.common\",\"doc\":\"\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"default\":null},{\"name\":\"name\",\"type\":\"string\",\"default\":null}]}"

// UserSubject schema registry subject
const UserSubject = "com.sarrubia.avro.example.common.User"

// UserBase
type UserBase struct {
	Id   string `avro:"id"`
	Name string `avro:"name"`
}

// Schema [REQUIRED] returns the schema const that belongs to User
// Important: the receiver MUST NOT be a pointer in order to assert true against schema.EventSchemaInterface
func (e UserBase) Schema() string {
	return UserAVSC
}
