/*This file has been autogenerated, please do not edit it.*/

package com_sarrubia_eventbus_avro_example_embedded

// EventMetadataEmbeddedAddedAVSC Avro schema to send to Schema Registry
const EventMetadataEmbeddedAddedAVSC = "{\"type\":\"record\",\"name\":\"EventMetadataEmbeddedAdded\",\"namespace\":\"com.sarrubia.eventbus.avro.example.embedded\",\"doc\":\"\",\"fields\":[{\"name\":\"id\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"key\",\"type\":[\"null\",{\"avro.java.string\":\"String\",\"type\":\"string\"}],\"default\":null},{\"name\":\"versionNumber\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"creation\",\"type\":\"long\",\"default\":0},{\"name\":\"type\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"},\"default\":\"NONE\"}]}"

// EventMetadataEmbeddedAddedSubject schema registry subject
const EventMetadataEmbeddedAddedSubject = "com.sarrubia.eventbus.avro.example.embedded.EventMetadataEmbeddedAdded"

// EventMetadataEmbeddedAddedBase
type EventMetadataEmbeddedAddedBase struct {
	Id            string  `avro:"id"`
	Key           *string `avro:"key"`
	VersionNumber string  `avro:"versionNumber"`
	Creation      int64   `avro:"creation"`
	Type          string  `avro:"type"`
}

// Schema [REQUIRED] returns the schema const that belongs to EventMetadataEmbeddedAdded
// Important: the receiver MUST NOT be a pointer in order to assert true against schema.EventSchemaInterface
func (e EventMetadataEmbeddedAddedBase) Schema() string {
	return EventMetadataEmbeddedAddedAVSC
}
