/*This file has been autogenerated, please do not edit it.*/

package com_sarrubia_eventbus_avro_example_embedded

// UserDataAVSC Avro schema to send to Schema Registry
const UserDataAVSC = "{\"type\":\"record\",\"name\":\"UserData\",\"namespace\":\"com.sarrubia.eventbus.avro.example.embedded\",\"doc\":\"example app' schema\",\"fields\":[{\"name\":\"email\",\"type\":{\"type\":\"string\"},\"default\":\"NONE\"},{\"name\":\"password\",\"type\":{\"type\":\"string\"},\"default\":\"NONE\"}]}"

// UserDataSubject schema registry subject
const UserDataSubject = "com.sarrubia.eventbus.avro.example.embedded.UserData"

// UserDataBase example app' schema
type UserDataBase struct {
	Email    string `avro:"email"`
	Password string `avro:"password"`
}

// Schema [REQUIRED] returns the schema const that belongs to UserData
// Important: the receiver MUST NOT be a pointer in order to assert true against schema.EventSchemaInterface
func (e UserDataBase) Schema() string {
	return UserDataAVSC
}
