name: {{__NAME__}}
on:
  pull_request:
    branches:
      - main
    paths:
      - '{{__PATH__}}/**'
  push:
    branches:
      - main
    paths:
      - '{{__PATH__}}/**'

jobs:
  ci-cd:
    uses: ./.github/workflows/subdomain.ci-cd.yml
    with:
      domain: '{{__DOMAIN__}}'
      subdomain: '{{__SUBDOMAIN__}}'
      subdomainPath: '{{__PATH__}}'