/*This file has been autogenerated, please do not edit it.*/

package com_sarrubia_avro_domain_subdomainB

// UserLoginAttemptEventAVSC Avro schema to send to Schema Registry
const UserLoginAttemptEventAVSC = "{\"type\":\"record\",\"name\":\"UserLoginAttemptEvent\",\"namespace\":\"com.sarrubia.avro.domain.subdomainB\",\"doc\":\"example app' schema\",\"fields\":[{\"name\":\"email\",\"type\":\"string\",\"default\":\"NONE\"},{\"name\":\"ip\",\"type\":\"string\",\"default\":\"NONE\"},{\"name\":\"dateD\",\"type\":\"long\",\"default\":0},{\"name\":\"result\",\"type\":\"string\",\"default\":\"NONE\"}]}"

// UserLoginAttemptEventSubject schema registry subject
const UserLoginAttemptEventSubject = "com.sarrubia.avro.domain.subdomainB.UserLoginAttemptEvent"

// UserLoginAttemptEventBase example app' schema
type UserLoginAttemptEventBase struct {
	Email  string `avro:"email"`
	Ip     string `avro:"ip"`
	DateD  int64  `avro:"dateD"`
	Result string `avro:"result"`
}

// Schema [REQUIRED] returns the schema const that belongs to UserLoginAttemptEvent
// Important: the receiver MUST NOT be a pointer in order to assert true against schema.EventSchemaInterface
func (e UserLoginAttemptEventBase) Schema() string {
	return UserLoginAttemptEventAVSC
}
