/*This file has been autogenerated, please do not edit it.*/

package com_sarrubia_avro_example_storage

// DbRecordAVSC Avro schema to send to Schema Registry
const DbRecordAVSC = "{\"type\":\"record\",\"name\":\"DbRecord\",\"namespace\":\"com.sarrubia.avro.example.storage\",\"doc\":\"\",\"fields\":[{\"name\":\"rName\",\"type\":\"string\",\"default\":null},{\"name\":\"rValue1\",\"type\":\"string\",\"default\":null},{\"name\":\"rSize\",\"type\":\"long\",\"default\":null}]}"

// DbRecordSubject schema registry subject
const DbRecordSubject = "com.sarrubia.avro.example.storage.DbRecord"

// DbRecordBase
type DbRecordBase struct {
	RName   string `avro:"rName"`
	RValue1 string `avro:"rValue1"`
	RSize   int64  `avro:"rSize"`
}

// Schema [REQUIRED] returns the schema const that belongs to DbRecord
// Important: the receiver MUST NOT be a pointer in order to assert true against schema.EventSchemaInterface
func (e DbRecordBase) Schema() string {
	return DbRecordAVSC
}
