name: example.common
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/avro/schm/example/common/**'
  push:
    branches:
      - main
    paths:
      - 'src/avro/schm/example/common/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  ci-cd:
    uses: ./.github/workflows/subdomain.ci-cd.yml
    secrets: inherit
    with:
      domain: 'example'
      subdomain: 'common'
      subdomainPath: 'src/avro/schm/example/common'