name: go-cd
on:
  push:
    branches:
      - main
    paths:
      - 'src/avro/schemas/**'

jobs:
  build:
    name: Genereate Go Models
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run avro2go
        run: ./go/cmd/avro2go -input-dir="src/avro/schemas" -output-dir="go/models"

      - name: Version from properties
        id: tag_version
        run: echo "::set-output name=number::$(./go/cmd/goProperties -file='gradle.properties' -prop='version')"

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add . 
          git commit -m "Adding Go models from Avro schema by bot"
          git tag -m "Version ${{ steps.tag_version.outputs.number }}" -a v${{ steps.tag_version.outputs.number }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          tags: true
