name: go-cd
on:
  push:
    branches:
      - main
    paths:
      - 'src/avro/schemas/**'

jobs:
  build:
    name: Genereate Go Models
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Autogenerate version
        run: make version FILENAME=version.properties GITHUB_RUN_ID=${{ github.run_id }}

      - name: Checking version
        run: sh go/cmd/checkTag.sh version.properties

      - name: Run avro2go
        run: ./go/cmd/avro2go -input-dir="src/avro/schemas" -output-dir="go/models"

      - name: Version from properties
        id: tag_version
        run: echo "::set-output name=number::$(./go/cmd/goProperties -file='version.properties' -key='version')"

      - name: Write Changelog
        run: |
          echo "## v${{ steps.tag_version.outputs.number }}" >> CHANGES.md

      - name: Fetch modified files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          NL='\n'
          CHANGE="## v${{ steps.tag_version.outputs.number }}${NL}"
          mapfile -d ',' -t added_files < <(printf '%s,' '${{ steps.files.outputs.added }}')
          if [ "${#added_files[@]}" -gt "0" ]
          then
            BLOCK="#### Added${NL}"
            for file in "${added_files[@]}"; do
              BLOCK+="- ${file}${NL}"
            done
            BLOCK+=${NL}
            CHANGE+=$BLOCK
          fi
          mapfile -d ',' -t removed_files < <(printf '%s,' '${{ steps.files.outputs.removed }}')
          if [ "${#removed_files[@]}" -gt "0" ]
          then
            BLOCK="#### Removed${NL}"
            for file in "${removed_files[@]}"; do
              BLOCK+="- ${file}${NL}"
            done
            BLOCK+=${NL}
            CHANGE+=$BLOCK
          fi
          mapfile -d ',' -t renamed_files < <(printf '%s,' '${{ steps.files.outputs.renamed }}')
          if [ "${#renamed_files[@]}" -gt "0" ]
          then
            BLOCK="#### Renamed${NL}"
            for file in "${renamed_files[@]}"; do
              BLOCK+="- ${file}${NL}"
            done
            BLOCK+=${NL}
            CHANGE+=$BLOCK
          fi
          mapfile -d ',' -t modified_files < <(printf '%s,' '${{ steps.files.outputs.modified }}')
          if [ "${#modified_files[@]}" -gt "0" ]
          then
            BLOCK="#### Modified${NL}"
            for file in "${modified_files[@]}"; do
              BLOCK+="- ${file}${NL}"
            done
            BLOCK+=${NL}
            CHANGE+=$BLOCK
          fi
          echo -e $CHANGE >> CHANGES.md

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add . 
          git commit -m "Adding Go models from Avro schema by bot"
          git tag -m "Version ${{ steps.tag_version.outputs.number }}" -a v${{ steps.tag_version.outputs.number }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          tags: true
