name: go-ci
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/avro/schemas/**'

jobs:
  code:
    name: Genereate Go Models
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run avro2go
        run: ./go/cmd/avro2go -input-dir="src/avro/schemas" -output-dir="go/models"
