name: Subdomain B
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/avro/schm/domain/subdomainB/**'
  push:
    branches:
      - main
    paths:
      - 'src/avro/schm/domain/subdomainB/**'

jobs:
  ci-cd:
    uses: ./.github/workflows/subdomain.ci-cd.yml
    with:
      subdomainPath: 'src/avro/schm/domain/subdomainB'